### ISSUE TITLE
dat fiind ca favourite e tot timpul false, puteai sa-i faci un constructor care sa aiba implicit false

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs14.homework#4]
https://github.com/cezarhre/curs14.homework/blob/ba0c1160aebe72419bcee55c21ff3380d4fc6d92/src/main/java/ro/fasttrackit/curs14/homework/QuoteReadFile.java#L31

**Comment by cezarhre** [comment]
Am scos parametrul din constructor
